// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPjI3ERXkJiBuyJ54cQ2uC9tTdcmc9Qg',
    appId: '1:731679973063:web:0a7227a978d4f21ca728e2',
    messagingSenderId: '731679973063',
    projectId: 'pesa-barbaadi',
    authDomain: 'pesa-barbaadi.firebaseapp.com',
    storageBucket: 'pesa-barbaadi.firebasestorage.app',
    measurementId: 'G-NQDFT4KKLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHehQaqHDiH0kgg2_0K1R0S_R8X5TABU',
    appId: '1:731679973063:android:c7d2178d51e490c4a728e2',
    messagingSenderId: '731679973063',
    projectId: 'pesa-barbaadi',
    storageBucket: 'pesa-barbaadi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcnj2e53G9sXv4ByiWYhKCbY4f78_yRIw',
    appId: '1:731679973063:ios:dcb9d1b614861fb2a728e2',
    messagingSenderId: '731679973063',
    projectId: 'pesa-barbaadi',
    storageBucket: 'pesa-barbaadi.firebasestorage.app',
    androidClientId: '731679973063-jtfblsfap0aud13asm95jkuqd289q8es.apps.googleusercontent.com',
    iosClientId: '731679973063-5uhktrgep0tvmmet4s48lq949ui8idk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pesaBarbaadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcnj2e53G9sXv4ByiWYhKCbY4f78_yRIw',
    appId: '1:731679973063:ios:dcb9d1b614861fb2a728e2',
    messagingSenderId: '731679973063',
    projectId: 'pesa-barbaadi',
    storageBucket: 'pesa-barbaadi.firebasestorage.app',
    androidClientId: '731679973063-jtfblsfap0aud13asm95jkuqd289q8es.apps.googleusercontent.com',
    iosClientId: '731679973063-5uhktrgep0tvmmet4s48lq949ui8idk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pesaBarbaadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVPjI3ERXkJiBuyJ54cQ2uC9tTdcmc9Qg',
    appId: '1:731679973063:web:29b6861fe8fe0620a728e2',
    messagingSenderId: '731679973063',
    projectId: 'pesa-barbaadi',
    authDomain: 'pesa-barbaadi.firebaseapp.com',
    storageBucket: 'pesa-barbaadi.firebasestorage.app',
    measurementId: 'G-9CJYCF7GZX',
  );
}
